[gcp_service_account]
type = "service_account"
project_id = "bt4103-c38a8"
private_key_id = "140a7b750577b5112978057c707306cbc2192210"

private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDRSaKS5JSJAaeA
N0KyygJS1eA1SWE3pS7sT0N+wQUNdGO6DS78hPbyT5ec7a5V12sFJz5VSCjRLKlF
cuhTJS2ZJiDWhberzX6BX0seZJWsm6H0kPcBPtTTEM5MbQkP7l8Km1SxWy7vmoTn
iH86SX9xJ7D6HT8AY7aJxQYH3fdi3OKLD1sBp3IiLSBji66Zk0t/nS1lT+tl/fGM
RejVnsVERTD0uLzfrfoSE+su4+frjNldQVkxpljPyIcR7GfRvOPRYymYbmBfEbOX
SRb1jXMqLjaY2HqLNJM5OR3SluowOBwhFHixgC0A96+Fb3Tvwsi/vFhkuHbCDzE3
aKJ2cPlZAgMBAAECggEAB55+hYo+iZPWtx1b52IhDka0wj/dAw93izkSABjzEAO1
FzqAY8dL7bOd1YPWIVAluGLuuyBUwxO1CF8X6+H6PF1129Vzo7SoFrnjRFSdWdKz
JVILOf+BdDskBYaBKlQvX9WaklfbWDP4A21V02eGVRZgtCRRLTiUFkUm1G29YjsP
MQOHoBTiIuCVEwMVCdk6kTINmj3O1jgVe7HNMf5veCuuhACWafkenQaqTdLJKysY
HRXP3mlDtNRBkr1/cbNfHIDRbV0QTFrfpGJ8Pj7HTf8/5oGleOAuON8Ad4+V+vFV
9AraXVXp1lpCWAao0QWO2Jhh0MvMq8eYu/khEs/IoQKBgQD/oKWuzbEeCqCsMX4n
jyrgl5XxjW/G5WX2RJSB6Rla0H+jn6o3foU3DiXMuI7GmgyQTT/u8S1cCW6vheZV
jWZPIFDsp0m4R0m8DiYp5dRFhNUII2UyAdBHJGlOEvOf6MJFTC3fqlJ8kY1R03iu
tf4U8lsqWuyyXpSq7KgHUi/5oQKBgQDRl7PQblTckvjDXxZ+sTblJ2bYPSy0cJ1g
3/xO2BEbypK2h0ZMWBNVRiFKqCmzu0u0tBzVrHDEN/hmHqp1jNMRHgpD5Zig6aNM
UFJg2gSvHJ4r+hRJWjs0dO1IQEhdLIjowAZ2PkJ5G55icHiz1NdRwWsPksNcdjoh
elcgfiUUuQKBgEm5Ni986SkF3aLrvzt/gdk2PqtkpCkTvd1RmBcDeCmF2loBUWEh
3x+qt+IcFClZAmiXrumlqvRRUBfVIUHpPulxI4WtFYjNHona9sy8mQTXs2zecHAE
r+HksW4v7w1eXrEHsG9COvnsLHq9559To4y8/OfxQzSKLIxDJo69+FIhAoGBAMrF
ZaWE2Hz9g8YgPHcdo+pXEFyr8pAvU1Lh4Au3ZfXpKb+FaDF8FFgvnQ3JW28TCM8u
YacnSYHMVHkXufo34AtzcKL3gY5L+zxdiRVCV73ChhQtwWql7Rl29gksh9X8vAfR
n27OFSlt2vGJtnzksdvasGVEq9TMXLj+z0QURnOhAoGAbuqjiGnhRe2jhb3rXi47
lSeWKw9ax+7iozNlwSwK0AzEzY/2GXrYh1BQ65sj8WDUkQlgeZlEof//YDLhIpNi
Mq1A0qb/J869v7UAPuAE5TFc3n9s6uZoW6ON4pPZi8UJM9wDwznJCQuggK2fRLSV
7+S1m74mpxSEnIyI6ZLWkfk=
-----END PRIVATE KEY-----\n
"""

client_email = "firebase-adminsdk-fbsvc@bt4103-c38a8.iam.gserviceaccount.com"
client_id = "111537008916507312545"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40bt4103-c38a8.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
